(define (problem pyramid-problem)
    (:domain pyramid-domain)
    (:objects 
        n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 - NUMBER
        S2 H5 D7 C8 DK D5 HA HX D2 H4 S9 D6 C3 C7 HJ H2 S5 CJ S7 SX SQ S8 SK H9 S6 D8 DJ - CARD
    )
    (:init
        (sum-equal-13 n0 n13)
        (sum-equal-13 n1 n12)
        (sum-equal-13 n2 n11)
        (sum-equal-13 n3 n10)
        (sum-equal-13 n4 n9)
        (sum-equal-13 n5 n8)
        (sum-equal-13 n6 n7)
        (sum-equal-13 n7 n6)
        (sum-equal-13 n8 n5)
        (sum-equal-13 n9 n4)
        (sum-equal-13 n10 n3)
        (sum-equal-13 n11 n2)
        (sum-equal-13 n12 n1)
        (sum-equal-13 n13 n0)


        (value S2 n2)
        (value H5 n5)
        (value D7 n7)
        (value C8 n8)
        (value DK n13)
        (value D5 n5)
        (value HA n1)
        (value HX n10)
        (value D2 n2)
        (value H4 n4)
        (value S9 n9)
        (value D6 n6)
        (value C3 n3)
        (value C7 n7)
        (value HJ n11)
        (value H2 n2)
        (value S5 n5)
        (value CJ n11)
        (value S7 n7)
        (value SX n10)
        (value SQ n12)
        (value S8 n8)
        (value SK n13)
        (value H9 n9)
        (value S6 n6)
        (value D8 n8)
        (value DJ n11)

        (covers H5 S2)
        (covers D7 S2)
        (covers C8 H5)
        (covers DK H5)
        (covers DK D7)
        (covers D5 D7)
        (covers HA C8)
        (covers HX DK)
        (covers HX D5)
        (covers D2 D5)
        (covers H4 HA)
        (covers S9 HX)
        (covers S9 D2)
        (covers D6 D2)

        (covers C3 C7)
        (covers C7 HJ)
        (covers HJ H2)
        (covers H2 S5)
        (covers S5 CJ)
        (covers CJ S7)
        (covers S7 SX)
        (covers SX SQ)
        (covers SQ S8)
        (covers S8 SK)
        (covers SK H9)
        (covers H9 S6)
        (covers S6 D8)
        (covers D8 DJ)

        (pyramid S2)
        (pyramid H5)
        (pyramid D7)
        (pyramid C8)
        (pyramid DK)
        (pyramid D5)
        (pyramid HA)
        (pyramid HX)
        (pyramid D2)
        (pyramid H4)
        (pyramid S9)
        (pyramid D6)
        
        (deck C3)
        (deck C7)
        (deck HJ)
        (deck H2)
        (deck S5)
        (deck CJ)
        (deck S7)
        (deck SX)
        (deck SQ)
        (deck S8)
        (deck SK)
        (deck H9)
        (deck S6)
        (deck D8)
        (deck DJ)

    )
    (:goal
        (not 
            (exists (?x - CARD)
                (pyramid ?x)
            )
        )
     ;   (exists (?x - CARD) (matched ?x))
;        (and
 ;           (waste C3)
  ;          (waste C7)
   ;     )
    )
)
